# Generated by Django 4.2.21 on 2025-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0021_formsubmission_honeypot_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(default='default', max_length=15, verbose_name='Action backend'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='language',
            field=models.CharField(default='de', max_length=10, verbose_name='form language'),
        ),
        migrations.AlterField(
            model_name='submittedtobesent',
            name='language',
            field=models.CharField(default='de', max_length=10, verbose_name='form language'),
        ),
    ]
