# Generated by Django 4.1.13 on 2026-06-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aldryn_forms", "0022_auto_20250508_0951"),
        ("aldryn_forms", "0023_alter_formplugin_action_backend_and_more"),
    ]

    operations = []
